//// <auto-generated />
//using System;
//using Inocrea.CodaBox.ApiServer.Entities;
//using Microsoft.EntityFrameworkCore;
//using Microsoft.EntityFrameworkCore.Infrastructure;
//using Microsoft.EntityFrameworkCore.Metadata;
//using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

//namespace Inocrea.CodaBox.ApiServer.Migrations
//{
//    [DbContext(typeof(InosysDBContext))]
//    partial class InosysDBContextModelSnapshot : ModelSnapshot
//    {
//        protected override void BuildModel(ModelBuilder modelBuilder)
//        {
//#pragma warning disable 612, 618
//            modelBuilder
//                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
//                .HasAnnotation("Relational:MaxIdentifierLength", 128)
//                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//            modelBuilder.Entity("Inocrea.CodaBox.ApiModel.Models.CodaIdentity", b =>
//                {
//                    b.Property<int>("CodaIdentityId")
//                        .ValueGeneratedOnAdd()
//                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//                    b.Property<string>("Login");

//                    b.Property<string>("Pwd");

//                    b.Property<string>("XCompany");

//                    b.HasKey("CodaIdentityId");

//                    b.ToTable("CodaIdentities");
//                });

//            modelBuilder.Entity("Inocrea.CodaBox.ApiModel.Models.CompteBancaire", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//                    b.Property<string>("Bic")
//                        .HasMaxLength(255)
//                        .IsUnicode(false);

//                    b.Property<string>("CurrencyCode")
//                        .HasMaxLength(255)
//                        .IsUnicode(false);

//                    b.Property<string>("Iban")
//                        .IsRequired()
//                        .HasMaxLength(255)
//                        .IsUnicode(false);

//                    b.Property<string>("IdentificationNumber")
//                        .HasMaxLength(255)
//                        .IsUnicode(false);

//                    b.HasKey("Id")
//                        .HasName("CompteBancaire_pk")
//                        .HasAnnotation("SqlServer:Clustered", false);

//                    b.ToTable("CompteBancaire");
//                });

//            modelBuilder.Entity("Inocrea.CodaBox.ApiModel.Models.SepaDirectDebit", b =>
//                {
//                    b.Property<int>("SepaDirectDebitId")
//                        .ValueGeneratedOnAdd()
//                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//                    b.Property<string>("CreditorIdentificationCode");

//                    b.Property<string>("MandateReference");

//                    b.Property<int>("PaidReason");

//                    b.Property<int>("Scheme");

//                    b.Property<int>("TransactionId");

//                    b.Property<int>("Type");

//                    b.HasKey("SepaDirectDebitId");

//                    b.HasIndex("TransactionId")
//                        .IsUnique();

//                    b.ToTable("SepaDirectDebits");
//                });

//            modelBuilder.Entity("Inocrea.CodaBox.ApiModel.Models.Statements", b =>
//                {
//                    b.Property<int>("StatementId")
//                        .ValueGeneratedOnAdd()
//                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//                    b.Property<int>("CompteBancaireId");

//                    b.Property<DateTime>("Date")
//                        .HasColumnType("date");

//                    b.Property<string>("InformationalMessage")
//                        .HasMaxLength(255)
//                        .IsUnicode(false);

//                    b.Property<double>("InitialBalance");

//                    b.Property<double>("NewBalance");

//                    b.HasKey("StatementId")
//                        .HasName("Statements_pk")
//                        .HasAnnotation("SqlServer:Clustered", false);

//                    b.HasIndex("CompteBancaireId");

//                    b.ToTable("Statements");
//                });

//            modelBuilder.Entity("Inocrea.CodaBox.ApiModel.Models.Transactions", b =>
//                {
//                    b.Property<int>("Id")
//                        .ValueGeneratedOnAdd()
//                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

//                    b.Property<int?>("AdresseId");

//                    b.Property<double>("Amount");

//                    b.Property<int>("CompteBancaireId");

//                    b.Property<string>("Message")
//                        .HasMaxLength(255)
//                        .IsUnicode(false);

//                    b.Property<int>("StatementId")
//                        .HasColumnName("StatementID");

//                    b.Property<string>("StructuredMessage")
//                        .IsRequired()
//                        .HasMaxLength(255)
//                        .IsUnicode(false);

//                    b.Property<DateTime>("TransactionDate")
//                        .HasColumnType("datetime");

//                    b.Property<DateTime>("ValueDate")
//                        .HasColumnType("datetime");

//                    b.HasKey("Id")
//                        .HasName("Transactions_pk")
//                        .HasAnnotation("SqlServer:Clustered", false);

//                    b.HasIndex("CompteBancaireId");

//                    b.HasIndex("StatementId");

//                    b.ToTable("Transactions");
//                });

//            modelBuilder.Entity("Inocrea.CodaBox.ApiModel.Models.SepaDirectDebit", b =>
//                {
//                    b.HasOne("Inocrea.CodaBox.ApiModel.Models.Transactions", "Transactions")
//                        .WithOne("SepaDirectDebit")
//                        .HasForeignKey("Inocrea.CodaBox.ApiModel.Models.SepaDirectDebit", "TransactionId")
//                        .OnDelete(DeleteBehavior.Cascade);
//                });

//            modelBuilder.Entity("Inocrea.CodaBox.ApiModel.Models.Statements", b =>
//                {
//                    b.HasOne("Inocrea.CodaBox.ApiModel.Models.CompteBancaire", "CompteBancaire")
//                        .WithMany("Statements")
//                        .HasForeignKey("CompteBancaireId")
//                        .HasConstraintName("Statements_CompteBanquare_fk");
//                });

//            modelBuilder.Entity("Inocrea.CodaBox.ApiModel.Models.Transactions", b =>
//                {
//                    b.HasOne("Inocrea.CodaBox.ApiModel.Models.CompteBancaire", "CompteBancaire")
//                        .WithMany("Transactions")
//                        .HasForeignKey("CompteBancaireId")
//                        .HasConstraintName("Transactions_CompteBancaires_fk");

//                    b.HasOne("Inocrea.CodaBox.ApiModel.Models.Statements", "Statement")
//                        .WithMany("Transactions")
//                        .HasForeignKey("StatementId")
//                        .HasConstraintName("Transactions_Statements_fk");
//                });
//#pragma warning restore 612, 618
//        }
//    }
//}
